#include "SDL3/SDL_stdinc.h"

#ifndef G_PATH_COMPARE_H
#define G_PATH_COMPARE_H 1

typedef enum _PathType
{
    None,
    Font1,
    FontHashTable1,
    FontPng1,
    DepthImage,
    CustomePath1,
    CustomePath2,
    CustomePath3,
    CustomePath4,
    LogPath,
    PathPath,
    CombineFragShader,
    Combine2dFragShader,
    CombineVertShader,
    BottomGlb,
    TestMtl,
    TestObj,
    Model3dVertShader,
    MainFontPng,
    Viking_room_CopyPng,
    ShadowVertShader,
    ShapeVertShader,
    Cornell_boxObj,
    Viking_roomObj,
    BoxObj,
    BoxPng,
    SSGICompShader,
    BottomObj,
    BottomPng,
    Model3dFragShader,
    ModelBottomFragShader,
    ShapeFragShader,
    VoxelMtl,
    VoxelObj,
    VoxelPng,
    MainBackgroundPng,
    Viking_roomPng,
    EmptyFragShader,
    MainBackgroundMusic1Wav,
    TestWav,
    EmojiHashTable,
    MainFontHashTable,
    EmojiFont,
    MainFont,
    ParticleCompShader,
    ParticleFragShader,
    ParticleVertShader,
    Spirv_reflectExe,
    TriangleFragShader,
    TriangleVertShader,
    TextTxt,
    CirclePng,
    EmojiPng,
    IconPng,
    Loading1Png,
    Non_existPng,
    ExitPng,
    LoadPng,
    SettingPng,
    StartPng,
    TextRectangle1Png,
    TileSet1Png,
    TileMap1TsdI,
    TileSet1Tsd,
    MAX_PATH_TYPE = 0x7FFFFFFF
} PathType;

extern PathType SDLCALL pathCompare(char * buffer);

#endif