#include "G_textureName.h"

#ifndef G_CONSTANTS_H
#define G_CONSTANTS_H 1

#define TEST 0

#define VERTEX_UNIT_SIZE_2D 32
#define INDEX_UNIT_SIZE_2D 2

#define VERTEX_COUNT_IN_UNIT_2D 4
#define INDEX_COUNT_IN_UNIT_2D 6

#define VERTEX_SIZE_2D VERTEX_UNIT_SIZE_2D * VERTEX_COUNT_IN_UNIT_2D
#define INDEX_SIZE_2D INDEX_UNIT_SIZE_2D * INDEX_COUNT_IN_UNIT_2D

#define MAX_UNIT_COUNT_2D (65535 / INDEX_COUNT_IN_UNIT_2D)

#define VERTEX_COUNT_IN_BUFFER_2D MAX_UNIT_COUNT_2D * VERTEX_COUNT_IN_UNIT_2D
#define INDEX_COUNT_IN_BUFFER_2D MAX_UNIT_COUNT_2D * INDEX_COUNT_IN_UNIT_2D

#define VERTEX_BUFFER_SIZE_2D VERTEX_SIZE_2D * MAX_UNIT_COUNT_2D
#define INDEX_BUFFER_SIZE_2D INDEX_SIZE_2D * MAX_UNIT_COUNT_2D

#define MAX_FRAMES_IN_FLIGHT 2

#define PARTICLE_COUNT 8192
#define BALLCOUNT 2000
#define MAX_CHARACTERS 100

#ifndef SEPRATOR
# if defined(_WIN32)
#  define SEPRATOR "\\"
# elif defined(__linux__)
#  define SEPRATOR "/"
# endif
#endif

#ifndef SEPRATOR_C
# if defined(_WIN32)
#  define SEPRATOR_C '\\'
# elif defined(__linux__)
#  define SEPRATOR_C '/'
# endif
#endif

#define LOGICAL_WIDTH 800
#define LOGICAL_HEIGHT 600

#define SHADOW_MAPPING_WIDTH 4096
#define SHADOW_MAPPING_HEIGHT 4096
#define SHADOW_SIZE 4096
#define LIGHT_HEIGHT 20.0f

// 1/sqrt(2)
#define HEIGHT_FACTOR 0.70710678118654752440084436210485f 

// #define BOTTOM_HEIGHT (800 / HEIGHT_FACTOR + 1)
#define BOTTOM_WIDTH 800
#define BOTTOM_HEIGHT 800
#define BOTTOM_LENGTH 800

#define TILE_WIDTH 16
#define TILE_HEIGHT 16

#define FONT_SIZE 24

#define MAX_MAP_GROUP 48
#define MAX_TILES_IN_GROUP 2500

#endif