#ifndef G_CONSTANTS_H
#define G_CONSTANTS_H 1

#define TEST 1

#define VERTEX_UNIT_SIZE 32
#define INDEX_UNIT_SIZE 2

#define VERTEX_COUNT_IN_UNIT 4
#define INDEX_COUNT_IN_UNIT 6

#define VERTEX_SIZE VERTEX_UNIT_SIZE * VERTEX_COUNT_IN_UNIT
#define INDEX_SIZE INDEX_UNIT_SIZE * INDEX_COUNT_IN_UNIT

#define MAX_UNIT_COUNT 250406

#define VERTEX_COUNT_IN_BUFFER MAX_UNIT_COUNT * VERTEX_COUNT_IN_UNIT
#define INDEX_COUNT_IN_BUFFER MAX_UNIT_COUNT * INDEX_COUNT_IN_UNIT

#define VERTEX_BUFFER_SIZE VERTEX_SIZE * MAX_UNIT_COUNT 
#define INDEX_BUFFER_SIZE INDEX_SIZE * MAX_UNIT_COUNT

#define MAX_FRAMES_IN_FLIGHT 2

#define PARTICLE_COUNT 8192
#define BALLCOUNT 2000
#define MAX_CHARACTERS 100

#ifndef SEPRATOR
# if defined(_WIN32)
#  define SEPRATOR "\\"
# elif defined(__linux__)
#  define SEPRATOR "/"
# endif
#endif

#ifndef SEPRATOR_C
# if defined(_WIN32)
#  define SEPRATOR_C '\\'
# elif defined(__linux__)
#  define SEPRATOR_C '/'
# endif
#endif

#define LOGICAL_WIDTH 800
#define LOGICAL_HEIGHT 600

#endif